### PR TITLE
`GLSR.Event` will be undefined when current page doesn't have any site-reviews sections

### PR DESCRIPTION
**Pull request by n0099**
also wrap it with in `DOMContentLoaded` event to prevent eager eval

### CODE REVIEW

**Comment by pryley** [comment]
This inline script is loaded on the page directly after the `site-reviews.js` script. For that reason, GLSR.Event should always be available to it. 

Also, the Site Reviews scripts are loaded globally. They are not dependant on the page content.

**Comment by n0099** [comment]
> This inline script is loaded on the page directly after the `site-reviews.js` script.

But any type of js aggregating optimize plugin such as autoptimize will break this execution order

**Comment by pryley** [comment]
Site Reviews uses the [wp_add_inline_script](http://developer.wordpress.org/reference/functions/wp_add_inline_script/) function to insert the inline script on the page. The first parameter of this function is the handle of the enqueued script that the inline script is dependant on.

Optimizing plugins generally take this into account when optimizing scripts, otherwise they would break a lot of plugins.

I'm guessing you created this pull request because you are experiencing this problem. If so, what is your setup like, what kind of optimisations are you doing, and which plugins are you using to do them (specifically)? 

I would like to be able to reproduce this issue.

**Comment by n0099** [comment]
I'm using WP Super Cache for pre-generated static html and autoptimize for js/css aggreated together.
Sometimes requesting the homepage, which haven't any reviews being shown, will trigger the calling Event on undefined error.
By adding breakpoint on the inline script I can see that `GLSR.Event` is undefined, and `window.GLSR` itself have a bunch of members.

**Comment by pryley** [comment]
I installed and enabled Autoptimizer and WP Super Cache.

These are the Autoptimizer settings for Javascript:

image

I created a new blank page with no content (Site Reviews or otherwise), and loaded it in a private window. After inspecting the aggregated autoptimizer script, this is the result:

image

**Comment by n0099** [comment]
Thanks for your test, but I have two separated scripts across the html and the aggregated js:
image
image
And I guess it's due to not enabling the `Also aggregate inline JS?` option for autoptimizer so it will only merge all enqueued scripts including the main `site-reviews.js`, but keeps all inline scripts as is, plus the aggregated js is loaded via `<script defer>`, leading to the inline part will get executed even before the aggregated js finish downloading.

Sadly I can't just enable this option since there are some per-post/user scripts echoed by php, if they also get merged, autoptimizer will produce tons of different aggregated js for every post that will miss any caching layer.

**Comment by pryley** [comment]
I see.

The problem here is that Autoptimize is breaking the website, not Site Reviews. What Autoptimize should be doing is manipulating the enqueue order to insert the aggregated script in the correct position in the DOM, instead of just dumping it at the end of the page (which breaks the inline scripts on the page).

Normally I would simply recommend that you exclude Site Reviews from the aggregated script, particularly since the Gzipped Size of the site-reviews.js file is only **10.52 KB**.

image

In this case, however, maybe a simple solution is just to change this:

https://github.com/pryley/site-reviews/blob/a3faef3992907d161b0478f90585f15e161ff776/plugin/Commands/EnqueuePublicAssets.php#L116

To this:

```php
        $script = 'window.hasOwnProperty("GLSR")||(window.GLSR={Event:{on:()=>{}}});';
```

This should also make the `site-reviews.js` script tag work with defer.

So, for example, if you decide to exclude site-reviews.js from Autoptimize's aggregated script, you would still be able to defer it like this without a console error:

```php
add_filter('site-reviews/defer-scripts', function ($handles) {
    $handles[] = 'site-reviews';
    return $handles;
});
```

And if you are using the add-ons and want the defer snippet above to still work:

```php
add_filter('site-reviews/optimize/js', '__return_true');
```

**Comment by n0099** [comment]
> In this case, however, maybe a simple solution is just to change this:

will this be introduced in next release?

**Pull request closed without merging**
