### PR TITLE
Simplify logic in isPhpValid

### PR DESCRIPTION
**Pull request by szepeviktor**
Just 1 line.

### CODE REVIEW

**Comment by pryley** [comment]
https://github.com/pryley/site-reviews/commit/9ebf8ec182885dd2054586b713bcbf6f5a208e29

**Comment by szepeviktor** [comment]
I've missed the 2nd one as I was eating pretzels 🥨 with raw parsley leaves 🍀

**Comment by pryley** [comment]
This is really a micro optimisation that is specific to the developer's preference of code readability, not performance.

**Comment by szepeviktor** [comment]
You know I research the root cause of problems of my SaaS manufacturer clients and frequently it is:

```php
const DEVELOPER_PREFERENCE = 4;

DEVELOPER_PREFERENCE = 5;
```

`PHP FATAL error: DEVELOPER_PREFERENCE cannot be changed.`

**Comment by pryley** [comment]
But that's sloppy code which can easily be caught with a linter. Readability preference is something else.

**Pull request closed without merging**
